- hosts: workstation
  gather_facts: false
  tasks:
  - name: Wait for connectivity from previous task
      pause:
        minutes: 2
  - name: OpenStack servers
    os_server_facts:
     cloud: openstack
     server: 'frontend'
    register: openstack_info
  - debug:
      msg: "{{ openstack_info }}"
    tags:
      - osp.smoke

  - name: Curl website
    command: curl "http://{{item.public_v4}}"
    with_items:
       - "{{ openstack_info.ansible_facts.openstack_servers }}"
    register: webpage

  - name: Fail if 'Ansible has done its job' is not in the page content
    fail:
    when: "'Ansible has done its job' not in webpage.results[0].stdout"
    tags:
      - osp.smoke
