# - name: yum clean
#   shell: yum clean all
- name: install pip
  dnf:
    name:
      - python3-pip
    state: latest
- name: Install openstacksdk library
  pip:
    name: openstacksdk
    executable: pip3
#   state: latest
    extra_args: -U
# - name: Create clouds.yaml file
#   blockinfile:
#     create: yes
#     path: /etc/openstack/clouds.yaml
#     block: |2
#       clouds:
#         ospcloud:
#           auth:
#             auth_url: http://192.0.2.21:5000/
#             password: r3dh4t1!
#             project_name: admin
#             username: admin
#           identity_api_version: '3.0'
#           region_name: RegionOne

- name: Create clouds.yaml file
  blockinfile:
    create: yes
    path: /etc/openstack/clouds.yaml
    block: |2
      clouds:
        openstack:
          auth:
            auth_url: http://192.0.2.21:5000/
            project_id: 4e07f423a12f437388a97a533bb9eef9
            password: r3dh4t1!
            project_name: admin
            username: admin
            user_domain_name: Default
          identity_api_version: "3"
          region_name: regionOne


- name: Set openstack.pub authorized key from file
  authorized_key:
    user: cloud-user
    state: present
    key: "{{ lookup('file', '/root/.ssh/openstack.pub') }}"
